# Generated by Django 4.2.6 on 2023-10-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_child_options_participant_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='question1_answer',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='survey',
            name='question2_answer',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='survey',
            name='question3_answer',
            field=models.CharField(default='', max_length=70),
        ),
    ]
