# Generated by Django 4.2.6 on 2023-10-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_survey_question1_answer_survey_question2_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='question1_answer',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question2_answer',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question3_answer',
            field=models.CharField(max_length=70),
        ),
    ]
