# Generated by Django 4.2.6 on 2023-10-20 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_survey_question1_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.participant'),
        ),
    ]
