# Generated by Django 4.2.6 on 2023-10-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_survey_question1_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='question10_answer',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='question4_answer',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='question5_answer',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='question6_answer',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='question7_answer',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='question8_answer',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='question9_answer',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survey',
            name='question1_answer',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=70),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question2_answer',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=70),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question3_answer',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=70),
        ),
    ]
