# Generated by Django 4.2.6 on 2023-10-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_mood"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="role",
            field=models.CharField(
                choices=[("parent", "parent"), ("child", "child")],
                default="child",
                max_length=70,
            ),
        ),
    ]
